-- Create an admin user: username=admin, password=admin123, role=Admin
-- Password hash for 'admin123' generated by bcryptjs with 10 salt rounds
INSERT INTO users (username, password_hash, role)
VALUES (
  'admin',
  '$2a$10$w5n5w9C8q9U5dA8M1JmD5e0nC0QOn/hw9Jb0T6pG4yQO5n8T6pQ5C', -- 'admin123'
  'Admin'
)
ON CONFLICT DO NOTHING;

-- Add sample drivers
INSERT INTO drivers (name, license_no) VALUES
  ('Alice Driver', 'DL123'),
  ('Bob Pilot', 'DL456')
ON CONFLICT DO NOTHING;

-- Add sample cars
INSERT INTO cars (license_plate, model, status) VALUES
  ('XYZ123', 'Toyota Prius', 'active'),
  ('ABC789', 'Honda Civic', 'active')
ON CONFLICT DO NOTHING;

-- Add sample assignment
INSERT INTO assignments (car_id, driver_id, assign_time)
  SELECT c.id, d.id, NOW()
  FROM cars c, drivers d
  WHERE c.license_plate = 'XYZ123' AND d.license_no = 'DL123'
ON CONFLICT DO NOTHING;